# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DateField(verbose_name='Wiek')),
                ('hight', models.IntegerField(verbose_name='Wzrost')),
                ('weight', models.IntegerField(verbose_name='Waga')),
                ('sex', models.IntegerField(choices=[(1, 'kobieta'), (2, 'mężczyzna')], verbose_name='Płeć')),
                ('activity', models.IntegerField(choices=[(1, 'Raczej niska'), (2, 'Umiarkowana aktywność'), (3, 'Aktywny tryb życia'), (4, 'Duża aktywność')], verbose_name='Aktywność fizyczna')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
