# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Fitapp.User')),
                ('age', models.DateField(verbose_name='Wiek')),
                ('hight', models.IntegerField(verbose_name='Wzrost')),
                ('weight', models.IntegerField(verbose_name='Waga')),
                ('sex', models.IntegerField(choices=[(1, 'kobieta'), (2, 'mężczyzna')], verbose_name='Płeć')),
                ('activity', models.IntegerField(choices=[(1, 'Raczej niska'), (2, 'Umiarkowana aktywność'), (3, 'Aktywny tryb życia'), (4, 'Duża aktywność')], verbose_name='Aktywność fizyczna')),
            ],
        ),
    ]
