# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-03 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitapp', '0002_auto_20170903_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity',
            field=models.IntegerField(blank=True, choices=[(0, 'Brak danych'), (1, 'Raczej niska'), (2, 'Umiarkowana aktywność'), (3, 'Aktywny tryb życia'), (4, 'Duża aktywność')], verbose_name='Aktywność fizyczna'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.DateField(blank=True, verbose_name='Wiek'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hight',
            field=models.IntegerField(blank=True, verbose_name='Wzrost'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'brak danych'), (1, 'kobieta'), (2, 'mężczyzna')], verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.IntegerField(blank=True, verbose_name='Waga'),
        ),
    ]
