# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitapp', '0002_auto_20170904_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Trener'), (1, 'Dietetyk'), (2, 'Klient'), (3, 'Trener/Dietetyk')], default=2, verbose_name='Rola'),
        ),
    ]
