# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 19:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fitapp', '0003_userprofile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.DateField(null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Trener'), (1, 'Dietetyk'), (2, 'Klient'), (3, 'Trener/Dietetyk'), (100, 'Manager')], default=2, verbose_name='Rola'),
        ),
    ]
