# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitapp', '0004_auto_20170906_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.DateField(blank=True, null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Wzrost'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'brak danych'), (1, 'kobieta'), (2, 'mężczyzna')], null=True, verbose_name='Płeć'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Waga'),
        ),
    ]
