# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fitapp', '0005_auto_20170906_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcoach',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientcoach',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity',
            field=models.IntegerField(choices=[(0, 'Brak danych'), (1, 'Raczej niska'), (2, 'Umiarkowana aktywność'), (3, 'Aktywny tryb życia'), (4, 'Duża aktywność')], default=0, null=True, verbose_name='Aktywność fizyczna'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(choices=[(0, 'brak danych'), (1, 'kobieta'), (2, 'mężczyzna')], default=0, null=True, verbose_name='Płeć'),
        ),
        migrations.DeleteModel(
            name='ClientCoach',
        ),
    ]
