# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fitapp', '0006_auto_20170906_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingsRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
