# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitapp', '0007_trainingsrelations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsrelations',
            name='relation',
        ),
        migrations.DeleteModel(
            name='TrainingsRelations',
        ),
    ]
