# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 00:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fitapp', '0009_trainings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainings',
            unique_together=set([('client', 'trainer')]),
        ),
    ]
